### ISSUE TITLE
Copy,Cut,Paste on Extend

### ISSUE THREAD

**Issue by powelleric** [DreymaR/BigBagKbdTrixXKB#12]
Thank you so much for this wonderful configuration.  I can't tell you how much it has made my life better!!  XKB was really hard to understand and I was not having any luck until I found your code.

I see that in the extend config it says that copy,paste, etc was: "not working since Ub14.04?".  I'm wondering if there is anything new in this regard.  

My intended use is not actually copy/paste but to create mappings to help on the command line.  For example, defaults are:
back a word  - alt+b
forward a word  - alt+f
delete word ahead - alt+d
delete to beginning  - ctrl+u 
delete to end - ctrl+k
etc....

As you can see, the functionality is scattered about on different sides of the keyboard and different modifiers.  I was hoping to make dedicated keys on the extend layer for each of these functions but I assume it will not work just like the copy/paste.

Thanks a bunch!!!

**Comment by DreymaR** [comment]
My copy/cut/paste Extend keys just send Ctrl+X/C/V which should work in most cases. The note concerns the multimedia keys named Copy/Cut/Paste which aren't directly supported and I don't think they are today but I'm not sure. If you were to revert the Extend mappings to using those multimedia keys for some reason, you could still bind them to actions in Ubuntu.

For actions like backing a word etc I use the Extend home row modifiers to chord. See the BigBag Extend topic for explanations. Example: Ext+T+N equals Ctrl+Left which goes back a word. Ext+S+T+Y is Ctrl+Shift+End which selects to the end of the text. Etc etc.

**Comment by powelleric** [comment]
Thank you so much for your response. I am definitely having trouble with the extend keys that send Ctrl+X, etc.  I just did a fresh install of my OS, KDE Neon, and still experience the issue.
I notice that this repository is tested on Ubuntu to 18.04.  So, I am going to install a fresh copy of that and then try again.  I will report back on how it goes.
On the bright side, I can confirm that basically everything else is working wonderfully.
Thank you again for all the work you put into this!

**Comment by DreymaR** [comment]
The Ubuntu version shouldn't matter, since very little essential content has changed in the xkb files.

Not sure what exactly your trouble with the Ctrl+X etc keys is, again?

**Comment by powelleric** [comment]
I'm happy to report that after switching to Ubuntu 18.04 that the issue is resolved: I am able to use the Undo, Cut, Copy shortcuts.

(Even though KDE Neon is based on Ubuntu, I feel that it might not be compatible with this repo.)
