### ISSUE TITLE
executable permissions missing on shell scripts

### ISSUE THREAD

**Issue by moesasji** [DreymaR/BigBagKbdTrixXKB#3]
Running the install-script fails on my machine with 

@@@ install-dreymar-xmod.sh - ERROR: Local files copy error! @@@

This is both in the downloaded archive and when I clone. This happens because the shell scripts do not have executable permission in the tree. 

It would be good to set the correct permissions for *.sh files to make it easier to install.

**Comment by DreymaR** [comment]
Try this again, please. The copy error should not be because of missing executable rights, I think.
