### ISSUE TITLE
How to Restore to Original Layout?

### ISSUE THREAD

**Issue by ohare93** [DreymaR/BigBagKbdTrixXKB#30]
Perhaps a stupid question, but I am stumped.

There is a reference in the help text to a `-#` option, but each time I run `./setxkb.sh -#` I get an error saying that is not an option :thinking:

**Comment by DreymaR** [comment]
No, there is no `-#` option. I usually substitute # for a generic number – in this case, a number or letter. What you read is the header explaining the rest of the help text.

I agree that restore-to-original could be handy, but then I'd have to store that somewhere. As it is, it's your own responsibility to know where you came from. If it was plain old US QWERTY, then the command `setxkbmap us` should do the trick for the layout. To ensure model and options are nulled out as well, `setxkbmap -model "pc104" -option "" -layout "us"`.

But how can I know what you had before? Maybe you have an ISO keyboard and want pc105 not pc104. Etc etc etc.

**Comment by ohare93** [comment]
Please do ignore my utter complete ignorance of these magical arts of keyboard input systems. This must be how my mum would feel if I tried to explain Docker :sweat_smile: 

That said, I was confused by: 
- the mention of a backup step when running install; 
- the header/legend of `-#` having the description "default"
- the existence of the folder "xkb-data_orig" (which I see now is in the source control, and so was not generated by me running the script); 
- and the general expectation that an undo command would exist :sweat_smile: 

None of the above are excuses, merely explanations of my ineptitude :grin:

**Comment by ohare93** [comment]
Great repo you have here, mate :+1: I eventually got things setup the way I wanted :grin: now I can continue my journey towards Colemak proficiency from 20 WPM back to my normal 70/80 WPM on Qwerty. Hell, I'd accept 50 WPM as long as this helps with the RSI :fearful: 

But I have to say it was a little bit bumpy to get there. Now that I'm out at the other end I can see a few things that I wish I knew at the start / were more clear in the documentation (in the README here, the xkb file itself, and on https://dreymar.colemak.org/ ) that could have greatly reduced my time to implementation. Us lowly fake-programmers like myself that don't touch any of this hardware key address nonsense need to have our hands held :grin: 

Lemme know if I should open another issue / PR with some of these suggestions :+1: if not, no worries.

**Comment by DreymaR** [comment]
I do believe the header/legend thing is understandable? At any rate, this is the first time I've heard of anyone not understanding it. Maybe if someone else complains about it, I'll remember your troubles and take action.

The orig folder in the source files holds the files originally in the xkb-data repo, that I've changed in the mod folder. I could've used a patch instead, but found this to be a slightly preferable way for me. The orig folder in the X11 dir is a backup of the files in the system xkb directory. It can be restored with a switch to the setxkb.sh script. So those two are not quite the same.

**Comment by ohare93** [comment]
> I do believe the header/legend thing is understandable? 

Not in my opinion. Specifically coming in as a complete noob that has not touched keyboard layouts and settings files in the past. Simple stuff like "Use the install script, don't use the set script" or "The install script will make create new keyboards in your system that you can select in your normal settings app" in a ReadMe would greatly improve the flow for someone such as myself to get things up and going. I know all that *now* but not coming into this blind.

Here are the issues / confusions I wrote down while getting things to work:

- XKB Repo
	- Install script
		- Not clear that it
			- Actually Installs the keyboard to the system
				- Simply says "Shell script to apply DreymaR's changes to the X keyboard files" in the help text
					- Non-keyboard-wizards who simply want Colemak don't know what this means
			- For all languages
			- Symbol and non symbols
				- Not clear they are both installed
				- Not clear what they each actually are
		- Does not seem to take the extra definition stuff
			- The "[--] [Setxkb ShortStr <kbd loc sym>]" options
			- They work on the setxkb script, but I found no difference when using the install script
				- Perhaps I did it wrong, but there was no warning or error
	- Set script
		- Not clear
			- That it should not be used
				- https://github.com/DreymaR/BigBagKbdTrixXKB/issues/8#issuecomment-738056559
			        - Should probably be moved into a sub folder
			- What exactly it does
			- That you can't bloody well go back! 😱
- https://dreymar.colemak.org/
	- Does not link to these repos
		- There is a Platform button at the top right, but it did nothing. Maybe broken?
- XKB file
	- Where is this file?
		- A command to open it would be useful
			- Should know where it is as in order to replace it it has to know where it is 🤔
	- Angle mod
		- Cannot be activated without also "setting the keyboard model" on your physical keyboard
	- DH mod
		- Is not enabled by default
		- No info on how to enable it
		- Surely should be a setting on the install script


Anything above may be unclear as I wrote it while working. Feel free and ask for clarification :+1: 

And again, take or leave my comments :+1: no worries at all.

**Comment by DreymaR** [comment]
I'll have to answer some of this bitwise. Please be patient.
> https://dreymar.colemak.org/

    Does not link to these repos
        There is a Platform button at the top right, but it did nothing. Maybe broken?

I have no idea why you say that. The platform icon works fine. The FAQ question "What's the platform icon for?" points to the Platforms section where there is a functioning platform box. When the Linux/Tux icon is selected, this box links both to the Forum XKB topic and the BigBag for XKB repo (this repo). Both links seem fine.

**Comment by DreymaR** [comment]
> XKB file
>    Where is this file? 

Not sure what you mean by that? There is no XKB file I know of. This repo contains lots of xkb-data files, that go in an xkb system directory. What are you referring to, please?
