### ISSUE TITLE
Broken xkb/rules/evdev.xml

### ISSUE THREAD

**Issue by AxelVoitier** [DreymaR/BigBagKbdTrixXKB#34]
Hello,

At first reboot after installing, gdm refused to start, and let me to deal with finding the issue from terminal.
I finally got to this:
![PXL_20230706_222554928](https://github.com/DreymaR/BigBagKbdTrixXKB/assets/284119/a9705e07-3b05-4dc6-89b7-2037c330df92)

Which lead me to this broken line:
https://github.com/DreymaR/BigBagKbdTrixXKB/blob/516e7bcdd66f155c65e43b111590013cebddbbb0/xkb-data_xmod/xkb/rules/evdev.xml#L2671

After fixing it, gdm accepted to start normally.

This was on a Ubuntu 20.04.
When I then installed on a 22.04, the behaviour was different. Gdm started fine, and I could log on. But keyboard was in qwerty for most windows, except, oddly for firefox and gimp, who were using the intended layout (4caws). I also noticed the layout selector in top right corner of gnome was missing.

After fixing the evdev.xml file in the same way, and rebooted, things went a bit better, but not fully. Ie. it's like most windows and gnome seems to use something like 4ca (which I have never configured or tried on this machine), but firefox and gimp do use the expected 4caws.

Maybe that one could be related to wayland. But I don't even know which compositor is used by default...

**Comment by DreymaR** [comment]
Thanks! That bug had been sitting around since June. Fixed now.

I think Ubuntu Wayland uses the Sway compositor by default? Looks like different programs respect different instructions, ugh.
