### ISSUE TITLE
`\` key is broken in pc104aw-zqu layout

### ISSUE THREAD

**Issue by alaviss** [DreymaR/BigBagKbdTrixXKB#4]
My keyboard configuration:
```
Option "XkbLayout" "us"
Option "XkbModel" "pc104aw-zqu"
Option "XkbVariant" "cmk_ed_us"
Option "XkbOptions" "misc:extend,lv5:caps_switch_lock,grp:shifts_toggle,compose:menu,keypad:pointerkeys,misc:cmk_curl_dh"
```

The `\` key generates no symbol whatsoever

```
KeyPress event, serial 33, synthetic NO, window 0x2000001,
    root 0xf5, subw 0x0, time 30662205, (244,77), root:(261,482),
    state 0x0, keycode 51 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
`xev` output on `\` keypress

**Comment by alaviss** [comment]
Commenting out [line 413 in file keycodes/evdev](https://github.com/DreymaR/BigBagKbdTrix_XKB/blob/68a482969d206f72234e1a12838a2cd8b0af2cd0/x-mod_v2-17-1ub1_2016-06-06/xkb/keycodes/evdev#L413) fixes the problem

**Comment by DreymaR** [comment]
Thanks! I suspect the alias <BKSL> = <AC12> may be the culprit. That line used to be commented out because it maps the key just like the default.

Could you test whether this line works:
    <BKSL> =  51;	// \	<  \

**Comment by alaviss** [comment]
It works nicely                                                                                                                                                                                                                                                                                                                                                     From: Øystein Bech GadmarSent: Tuesday, June 13, 2017 19:09To: DreymaR/BigBagKbdTrix_XKBReply To: DreymaR/BigBagKbdTrix_XKBCc: alaviss; AuthorSubject: Re: [DreymaR/BigBagKbdTrix_XKB] `\` key is broken in pc104aw-zqu layout (#4)Thanks! I suspect the alias  =  may be the culprit. That line used to be commented out because it maps the key just like the default.
Could you test whether this line works:
 =  51;	// \	<  \

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DreymaR/BigBagKbdTrix_XKB","title":"DreymaR/BigBagKbdTrix_XKB","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DreymaR/BigBagKbdTrix_XKB"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DreymaR in #4: Thanks! I suspect the alias \u003cBKSL\u003e = \u003cAC12\u003e may be the culprit. That line used to be commented out because it maps the key just like the default.\r\n\r\nCould you test whether this line works:\r\n    \u003cBKSL\u003e =  51;\t// \\\t\u003c  \\\r\n"}],"action":{"name":"View Issue","url":"https://github.com/DreymaR/BigBagKbdTrix_XKB/issues/4#issuecomment-308095666"}}}
